import { runReminderCron } from "./lib/cron-worker";
import { guardApiRequest, type ApiGuardEnv } from "./lib/api-guard";

// @ts-ignore Generated by `opennextjs-cloudflare build` before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";

export default {
  async fetch(request, env, ctx) {
    const rejection = await guardApiRequest(request, env);
    if (rejection) {
      console.warn("API request rejected", {
        method: request.method,
        pathname: new URL(request.url).pathname,
        status: rejection.status,
      });
      return rejection;
    }

    return openNextWorker.fetch(request, env, ctx);
  },

  async scheduled(_controller, env, ctx) {
    const result = await runReminderCron(
      (request) => openNextWorker.fetch(request, env, ctx),
      env.CRON_SECRET ?? process.env.CRON_SECRET,
    );
    console.log("Reminder cron completed", {
      sent: result.sent ?? 0,
      skipped: result.skipped ?? 0,
      alreadySent: result.alreadySent ?? 0,
    });
  },
} satisfies ExportedHandler<CloudflareEnv & ApiGuardEnv>;
